name: Publish image
on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: VERSION=0.93.0
          tags: nellcorp/statping:0.93.0,nellcorp/statping:latest 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.DOCKER_PASSWORD }}